/*
 * Copyright 2018 IKS Gesellschaft fuer Informations- und Kommunikationssysteme mbH
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.iksgmbh.sysnat.test.module_level;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.Test;

import com.iksgmbh.sysnat.GenerationRuntimeInfo;
import com.iksgmbh.sysnat.SysNatTestingExecutor;
import com.iksgmbh.sysnat.common.utils.SysNatFileUtil;

/**
 * Tests for the interaction of sysnat.testcase.generation and sysnat.test.execution.
 * The interaction takes place via files generated by sysnat.testcase.generation 
 * and written into sysnat.test.execution.
 * 
 * @author Reik Oberrath
 */
public class BDD_Keyword_Usage_ModuleLevelTest 
{
	private static final String EXECUTION_DIR = "../sysnat.test.execution/src/test/gen/";
	private static final String TESTDATA_DIR = "../sysnat.quality.assurance/src/test/resources/testdata/";

	private String testInputDir;

	@Before
	public void setup() {
		SysNatFileUtil.deleteFolder(EXECUTION_DIR);
		GenerationRuntimeInfo.reset();
		System.setProperty("sysnat.dummy.test.run", "true");
		System.setProperty("sysnat.autolaunch.report", "false");
	}

	@Test
	public void compilesAndExecutesXX_with_BDDKeyword() throws Exception
	{
		// arrange
		final String testAppName = "CalculatorBDDKeywordsTestApp";
		System.setProperty("sysnat.properties.path", TESTDATA_DIR + testAppName);
		System.setProperty("settings.config", TESTDATA_DIR + testAppName + "/settings.config");

		SysNatFileUtil.copyTextFileToTargetDir(TESTDATA_DIR + testAppName,
				"Calculator.java", 
				"../sysnat.test.execution/src/main/java/com/iksgmbh/sysnat/test");
		SysNatFileUtil.copyTextFileToTargetDir(TESTDATA_DIR + testAppName, 
				"CalculatorLanguageTemplatesContainer.java", 
                EXECUTION_DIR + "com/iksgmbh/sysnat/test/bddkeywordstestapp");
		SysNatFileUtil.copyTextFileToTargetDir(TESTDATA_DIR + testAppName, 
				"BDDKeywordTestCaseTest.java", 
                EXECUTION_DIR + "com/iksgmbh/sysnat/test/bddkeywordstestapp");
		
		GenerationRuntimeInfo.getInstance();
		
		// act
		final String result = SysNatTestingExecutor.startMavenCleanCompileTest();

		// assert
		assertEquals("Maven result", SysNatTestingExecutor.MAVEN_OK, result);
	}

}