package com.iksgmbh.sysnat.test.testcase_templates;

import com.iksgmbh.sysnat.annotation.LanguageTemplateContainer;
import com.iksgmbh.sysnat.test.templateContainer.ComplexInstructionTestApplication_LanguageTemplateContainer;

public class ComplexInstructionTestApplication_TestCaseTemplate 
{
	@LanguageTemplateContainer
	protected ComplexInstructionTestApplication_LanguageTemplateContainer languageTemplateContainerComplexInstructionTestApplication;
}
